name: "Hello world JS Action"
description: "Greet someone and record the time"

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'Radizzt'

outputs:
  time:
    description: 'The time we greeted you'

runs:
  using: 'node20'
  main: 'dist/index.js'